# Generated by Django 6.0.4 on 2026-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('typical_meal_time', models.IntegerField(choices=[(1, 'morning'), (2, 'afternoon'), (3, 'evening')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('number_of_votes', models.IntegerField(default=0)),
            ],
        ),
    ]
