# Generated by Django 6.0.4 on 2026-05-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews/meal_ratings/')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('date_of_rating', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='meals.meal')),
            ],
            options={
                'verbose_name': 'Meal Rating',
                'verbose_name_plural': 'Meal Ratings',
                'ordering': ['-date_of_rating'],
            },
        ),
    ]
